name: .NET Framework

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
      
    - name: Restore Packages
      run: nuget restore DirectoryBrowseLab.sln
    
    - name: Build Solution
      run: msbuild.exe DirectoryBrowseLab.sln
